### ISSUE TITLE
Problematic mime-types dependency via azure gem

### ISSUE THREAD

**Issue by tanordheim** [juliusl/logstash-input-azurewadtable#2]
The latest version of this gem depends on the `azure` gem with the version filter `~> 0.6.4`; and the latest 0.6 version of the `azure` gem depends on `mime-types ~> 1.0)`.

This causes a problem with the latest version of ElasticSearch that has some pre-existing dependencies also depending on `mime-types`, and attempting to install the plugin from RubyGems gives the following error:

```
# bin/plugin install logstash-input-azurewadtable
Validating logstash-input-azurewadtable
Installing logstash-input-azurewadtable
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 2.6.1)

  In Gemfile:
    coveralls (>= 0) java depends on
      rest-client (< 2, >= 1.6.8) java depends on
        mime-types (< 3.0, >= 1.16) java

    logstash-input-imap (>= 0) java depends on
      mail (>= 0) java depends on
        mime-types (< 3, >= 1.16) java

    logstash-input-azurewadtable (>= 0) java depends on
      azure (~> 0.6.4) java depends on
        mime-types (~> 1.0) java
```

Any chance we can have the `azure` gem dependency here bumped to `~> 0.7.0`, which has a `mime-types` dependency not conflicting with these?

**Comment by yshahin** [comment]
Any updates in this?

**Comment by juliusl** [comment]
Hi - Sorry for the very late reply, I've been working on other projects. I have updated this to use the latest azure so that should fix the issue. I need to run more testing before closing this issue, but it might be good to go. It will be 0.9.5 version of the gem. Thanks

**Comment by juliusl** [comment]
I believe I have fixed this issue. Sorry it took so long!
